### ISSUE TITLE
issues compiling for iOS

### ISSUE THREAD

**Issue by kheftel-old** [CollabPlus/ANE-Can-Open-URL#1] opened 2015-01-28 03:52 UTC
hi,

I just downloaded the zip of this repo, but when I use the ANE in my ios app (compiling in FB 4.7 on OSX 10.10), I get this:

```
Error occurred while packaging the application:

Undefined symbols for architecture armv7:
  "___divmodsi4", referenced from:
      __ZN12BlockedCodec12CalcGridSizeEiiPi in libRuntimeHMAOT.arm-air.a(ZlibCodec.o)
      __ZN12BlockedCodec11SetupBlocksEii in libRuntimeHMAOT.arm-air.a(ZlibCodec.o)
  "___udivmodsi4", referenced from:
      __ZN11FlashString9AppendIntEli in libRuntimeHMAOT.arm-air.a(flashstring.o)
      __ZN7avmplus6String12hashCodeUIntEj in libRuntimeHMAOT.arm-air.a(StringObject.o)
      _sqlite3BitvecSet in libRuntimeHMAOT.arm-air.a(sqlite3_all.o)
      _sqlite3BitvecTest in libRuntimeHMAOT.arm-air.a(sqlite3_all.o)
      _sqlite3BitvecClear in libRuntimeHMAOT.arm-air.a(sqlite3_all.o)
      __ZL10II_samplesP10mad_bitptrPK10quantclassPl in libRuntimeHMAOT.arm-air.a(layer12.o)
      __ZL14scale_rationalmmm in libRuntimeHMAOT.arm-air.a(madtimer.o)
      ...
ld: symbol(s) not found for architecture armv7
Compilation failed while executing : ld64
```

It looks similar to a non-universal .a error, but your version is specifically compiled for 64-bit, so I don't know what the problem is.

**Comment by kheftel-old** [comment] 2015-01-28 04:01
I figured it out - you have two .ane files.  The one in the bin/ folder produces the above error.  The one in the folder above works properly.

**Comment by gnanaprakash** [comment] 2015-01-28 05:02
Not sure how top level .ane created, any how I have reorganised .ane file to be under /bin folder. Btw,  I could confirm both the .ane has targeted for armv, arm64. Here is the command I used to confirm it

__On my terminal__
bash>unzip CanOpenUrl.ane
bash>file META-INF/ANE/iPhone-ARM/libCanOpenUrlIosExtension.a  
META-INF/ANE/iPhone-ARM/libCanOpenUrlIosExtension.a: Mach-O universal binary with 2 architectures
META-INF/ANE/iPhone-ARM/libCanOpenUrlIosExtension.a (for architecture armv7):	current ar archive random library
META-INF/ANE/iPhone-ARM/libCanOpenUrlIosExtension.a (for architecture arm64):	current ar archive random library

**Comment by gnanaprakash** [comment] 2015-01-28 05:03
Not sure how top level .ane created, any how I have reorganised .ane file to be under /bin folder. Btw,  I could confirm both the .ane has targeted for armv, arm64. Here is the command I used to confirm it

**On my terminal**
terminal$ lipo -info META-INF/ANE/iPhone-ARM/libCanOpenUrlIosExtension.a  
Architectures in the fat file: META-INF/ANE/iPhone-ARM/libCanOpenUrlIosExtension.a are: armv7 arm64

**Comment by kheftel-old** [comment] 2015-01-28 05:16
Thanks for adding 64-bit support!

**Comment by kheftel-old** [comment] 2015-01-28 06:40
I'm still getting that error, and I don't know why. Is there any chance it's because the ANE is not compiled for armv7s?  I followed your steps in the terminal and got the same output, but I'm still getting the same error. any ideas why?

**Comment by kheftel-old** [comment] 2015-01-28 06:42
I'm using AIR 16 SDK, btw.  Gonna try it again with AIR 15 and see if that helps.

**Comment by kheftel-old** [comment] 2015-01-28 07:07
by golly, reverting to AIR SDK v15 worked.

**Comment by gnanaprakash** [comment] 2015-01-28 08:11
Will try it on Air 16 and update

**Comment by Elegarret** [comment] 2015-01-28 13:01
I have the same error under AIR16, but... I have it even without canOpenURL.ane. So the problem is somewhere out there. Now trying to investigate...

**Comment by Elegarret** [comment] 2015-01-28 13:42
Well, that's what I found. There was one more bad ane in my project: sticksport's flurry ane. When I turned it off as well as canOpenURL.ane, project was finally built successfully. (actually they are not bad, but they don't work with AIR16)

Then I tried to turn on only canOpenURL.ane from this branch and error appeared again.

 So I can confirm that this canOpenURL.ane causes AIR16 to fail build.

**Comment by gnanaprakash** [comment] 2015-01-28 14:28
Yeah...I could hit the same problem as mentioned above using AIR 16, so have modified the platform options (platform.xml) to point minimum iOS SDK to 6.0 and minimum iOS target version to 6.0, with this change I could able to package .ipa using .ane and the same .ane is updated, so please test it on AIR 16 app and let me know

**Comment by Elegarret** [comment] 2015-01-28 15:54
It seems that everything is ok now! Thank you, @gnanaprakash !

BTW I had to restart flash develop and recompile .swf, otherwise error persisted

**Comment by kheftel-old** [comment] 2015-01-28 16:11
Yup, looking great with AIR 16!!  Thanks for the quick fix!

**Comment by tomlucient** [comment] 2015-02-04 21:23
Hi gnanaprakash, awesome of you to work on this. I've downloaded the ANE and am compiling with Flash CS6. When I add the ane into the library paths, I get an error "Warning: unable to load SWC CanOpenUrl.ane". When I point at the original stick sports ANE in the same way, I don't get that error. Any ideas why I would be getting this error?

**Comment by gnanaprakash** [comment] 2015-02-05 04:19
@tomlucient, 
I don't have experience using Flash CS, so not sure why that warning arise. The only difference between sticksports vs my version is that the iOS static library project has been recompiled to target both armv7, arm64 and all .swc compiled using latest version of AIR 16 + Flex 4.13. So may be you should match the AIR + Flex version to avoid that warning.

BTW, whether you are able to make it work even with warning or Flash CS wont allow to do so?

**Comment by gnanaprakash** [comment] 2015-02-10 03:58
Added support for iPhone-x86

**Comment by AntonPieter** [comment] 2015-02-13 12:27
I am going to check this out using latest version of AIR. If it works, you are a live saver!

**Comment by gnanaprakash** [comment] 2015-04-23 12:23
@tomlucient Do you still face an issue as reported? if not I will close this issue.

@AntonPieter Did you check it?

**Comment by tomlucient** [comment] 2015-04-23 18:18
I went with a different solution so I don't know if it was resolved.

thank you
Tom

Tom Anderson
mobile: (505) 463-1469

**Comment by Jacowaco** [comment] 2015-09-08 22:37
Hi, i tried to use the ANE found in the bin folder but when compiling my app to iOS i get:
Error: META-INF/ANE/iPhone-ARM/libCanOpenUrlIosExtension.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

Could you make the .ANE again? I don't have a Mac to make it

**Comment by gnanaprakash** [comment] 2015-09-09 10:18
I could able to confirm .ane has ARM support, here is what I could see after extracting .ane file using unzip
![screen shot 2015-09-09 at 3 49 45 pm](https://cloud.githubusercontent.com/assets/2527624/9759413/722e3532-570a-11e5-8c5b-e7f1beee486e.png)

**Comment by Jacowaco** [comment] 2015-09-09 17:10
You are right, i had downloaded both the SticksSports ANE and yours, and messed up. Sorry for wasting your time. Thanks for your quick answer!

**Comment by gnanaprakash** [comment] 2015-10-12 16:06
Not an issue as per @Jacowaco, so closing it

**Closed as completed** 2015-10-12 16:06 UTC
